version: '3.8'

services:
  # HearTalk AI MVP Service
  ai-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-service
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - heartalk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (for local development with hot reload)
  ai-service-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-service-dev
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - heartalk-network
    profiles:
      - dev

networks:
  heartalk-network:
    driver: bridge